definitions:
  handler.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  mock.JSONBody:
    properties:
      email:
        type: string
      username:
        type: string
    required:
    - email
    - username
    type: object
  mock.LoginBody:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  mock.RegisteredBody:
    properties:
      header_img:
        type: string
      nick_name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
  description: 基于Gin进行快速构建RESTful API 服务的脚手架
  license: {}
  title: go-one-server
  version: "1.0"
paths:
  /api/v1/mock/form:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 处理application/x-www-form-urlencoded类型的POST请求
      parameters:
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: form表单请求
      tags:
      - mock
  /api/v1/mock/get:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Get请求
      tags:
      - mock
  /api/v1/mock/json:
    post:
      description: 邮箱、用户名校验
      parameters:
      - description: 测试请求json参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/mock.JSONBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: JSON参数请求
      tags:
      - mock
  /api/v1/mock/login:
    post:
      parameters:
      - description: 登录信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/mock.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 用户登录
      tags:
      - mock用户
  /api/v1/mock/query:
    get:
      description: 查询参数，匹配 query?id=xxx
      parameters:
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: query参数查询
      tags:
      - mock
  /api/v1/mock/query/array:
    get:
      description: 数组参数，匹配多选业务如 array?ids=xxx&ids=xxx&ids=xxx,key一样，value不同
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: queryArray参数查询
      tags:
      - mock
  /api/v1/mock/query/map:
    get:
      description: map参数，字典参数，匹配 map?ids[a]=123&ids[b]=456&ids[c]=789
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: queryMap参数查询
      tags:
      - mock
  /api/v1/mock/registered:
    post:
      parameters:
      - description: 注册信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/mock.RegisteredBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 用户注册
      tags:
      - mock用户
  /api/v1/mock/uri/{id}:
    get:
      description: 路径参数，匹配 /uri/{id}
      parameters:
      - description: id值
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: uri参数请求
      tags:
      - mock
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
