definitions:
  handler.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  model.ApiInfo:
    properties:
      api_group:
        example: base
        type: string
      description:
        example: api中文描述
        type: string
      method:
        example: POST
        type: string
      path:
        example: /api/v1/api
        type: string
    required:
    - api_group
    - description
    - method
    - path
    type: object
  model.RoleInfo:
    properties:
      remark:
        example: 备注
        type: string
      role_key:
        example: 角色代码
        type: string
      role_name:
        example: 角色名
        type: string
    required:
    - role_key
    - role_name
    type: object
  v1.JSONBody:
    properties:
      email:
        type: string
      username:
        type: string
    required:
    - email
    - username
    type: object
  v1.casbinApiBody:
    properties:
      api_id_list:
        items:
          type: integer
        type: array
    required:
    - api_id_list
    type: object
  v1.loginBody:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: user1
        type: string
    required:
    - password
    - username
    type: object
  v1.registeredUserBody:
    properties:
      password:
        example: "123456"
        type: string
      re_password:
        example: "123456"
        type: string
      remark:
        example: 备注
        type: string
      username:
        example: user1
        type: string
    required:
    - password
    - re_password
    - username
    type: object
  v1.userRoleBody:
    properties:
      role_key:
        type: string
      username:
        example: user1
        type: string
    required:
    - role_key
    - username
    type: object
info:
  contact: {}
  description: 基于Gin进行快速构建RESTful API 服务的项目模板
  license: {}
  title: go-one-server
  version: "1.0"
paths:
  /api/v1/api:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 页面大小
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 分页获取API列表
      tags:
      - API
    post:
      parameters:
      - description: api信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.ApiInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 添加API
      tags:
      - API
  /api/v1/api/{id}:
    delete:
      parameters:
      - description: api ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 删除API
      tags:
      - API
  /api/v1/casbin/api/{role_key}:
    get:
      parameters:
      - description: 角色代码
        in: path
        name: role_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 查看角色权限
      tags:
      - casbin
    put:
      parameters:
      - description: 角色代码
        in: path
        name: role_key
        required: true
        type: string
      - description: 权限信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.casbinApiBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 更新角色权限
      tags:
      - casbin
  /api/v1/casbin/setUserRole:
    post:
      parameters:
      - description: 用户角色信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.userRoleBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 设置用户角色
      tags:
      - casbin
  /api/v1/examples/form:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 处理application/x-www-form-urlencoded类型的POST请求
      parameters:
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: form表单请求
      tags:
      - examples
  /api/v1/examples/get:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: Get请求
      tags:
      - examples
  /api/v1/examples/json:
    post:
      description: 邮箱、用户名校验
      parameters:
      - description: 测试请求json参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.JSONBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: JSON参数请求
      tags:
      - examples
  /api/v1/examples/query:
    get:
      description: 查询参数，匹配 query?id=xxx
      parameters:
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: query参数查询
      tags:
      - examples
  /api/v1/examples/query/array:
    get:
      description: 数组参数，匹配多选业务如 array?ids=xxx&ids=xxx&ids=xxx,key一样，value不同
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: queryArray参数查询
      tags:
      - examples
  /api/v1/examples/query/map:
    get:
      description: map参数，字典参数，匹配 map?ids[a]=123&ids[b]=456&ids[c]=789
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: queryMap参数查询
      tags:
      - examples
  /api/v1/examples/uri/{id}:
    get:
      description: 路径参数，匹配 /uri/{id}
      parameters:
      - description: id值
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: uri参数请求
      tags:
      - examples
  /api/v1/role:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 页面大小
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 分页获取角色列表
      tags:
      - 角色
    post:
      parameters:
      - description: 角色信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.RoleInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 添加角色
      tags:
      - 角色
  /api/v1/role/{role_key}:
    delete:
      parameters:
      - description: 角色代码
        in: path
        name: role_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      security:
      - ApiKeyAuth: []
      summary: 删除角色
      tags:
      - 角色
  /api/v1/user/login:
    post:
      parameters:
      - description: 登录信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.loginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 用户登录
      tags:
      - 用户
  /api/v1/user/registered:
    post:
      parameters:
      - description: 注册信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.registeredUserBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Response'
      summary: 用户注册
      tags:
      - 用户
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
